### PR TITLE
Prefix rules

### PR DESCRIPTION
**Pull request by DaveMcEwan**
- New rules for naming convention of interfaces, modules, and packages.
  - `prefix_interface`
  - `prefix_module`
  - `prefix_package`
  - `uppercamelcase_interface`
  - `uppercamelcase_module`
  - `lowercamelcase_package`
- New rule `prefix_instance` for prefix on instance names, defaulting to `"u_"`.
- Modified `generate_for_with_label` and `generate_if_with_label` to check for prefix.
  For old behaviour (only existence check), the `prefix_label`. option can be set to `""`.
- New rule `generate_case_with_label` similar to the above.

### CODE REVIEW

**Comment by dalance** [comment]
Thank you for a lot of controbution!
I think all rules are reasonable, but it may be better that the naming convention can be selectable.
For example, `uppercamelcase_interface`, `lowercamelcase_interface`, `snakecase_interface`.

**Comment by DaveMcEwan** [comment]
Okay cool. I'll add lower/uppercamelcase rules for packages, interfaces, and modules to this PR (soon).
I'd like to leave snakecase rules for a different PR though, if that's okay with you?

**Comment by DaveMcEwan** [comment]
I've now added the rules for `lowercamelcase_(interface|module)` and `uppercamelcase_package`.

After a bit more thinking, I'm not sure how `snakecase_*` checking would work. I often use a mix of CamelCase and snake_case like `PartOne_secondPart_PartThree`, i.e. underscores are used to separate CamelCase terms. This doesn't really need any more checking except that the first character is upper/lower case. So, I'd like to leave this PR with just the rules for lower/UpperCamelCase.

**Comment by dalance** [comment]
In my understanding, lower snake case `aa_bb_cc` and upper snake case `AA_BB_CC` are defined generally.
I don't know the name of combination of snake and camel case.
That aside, I agree the current PR. I'll merge this after checking the diff.

**Comment by dalance** [comment]
I merged and released v0.5.0.
Thanks!

**Pull request merged**
