### PR TITLE
Improvement Add document CONTRIBUTING.md, based on Verilator's one.

### PR DESCRIPTION
**Pull request by DaveMcEwan**
- Adding A New Rule section shows most of the working process.
- Copyright notice updated after emails with dalance.
  https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/
- List of contributors taken from https://github.com/dalance/svlint/graphs/contributors
- TODO beside each contributor to contact individually.
  @supleed2, @dpretet, @taichi-ishitani, @Raamakrishnan, @skjdbg, @akberg:
  1. Do you agree to be on the list of contributors?
  2. Can you certify your contributions under the (very short/simple) [Developer Certificate of Origin](https://developercertificate.org/)?

### CODE REVIEW

**Comment by taichi-ishitani** [comment]
@DaveMcEwan 

> TODO beside each contributor to contact individually

My answer for both questions is yes.

**Comment by akberg** [comment]
Yes at both from me as well. Happy to see the project is active!

**Comment by supleed2** [comment]
Yes for both :)

**Comment by DaveMcEwan** [comment]
Thanks folks :)
@skjdbg Would you like to provide a name?

**Comment by dpretet** [comment]
Yes for both ☺️

**Comment by DaveMcEwan** [comment]
I have received confirmation from Raamakrishnan (via both email and LinkedIn message) so that's all contributors now covered.
@dalance I think this is now ready.

**Comment by dalance** [comment]
Thanks all contributors!

**Pull request merged**
