### PR TITLE
Feature: Add some pre-configured and explained "rulesets" (TOML files) with wrapper scripts.

### PR DESCRIPTION
**Pull request by DaveMcEwan**
- `mdgen` reads from `md/ruleset-*.md` to extract wrapper scripts and TOML files from Markdown explanations.
I guess this is a form of [literate programming](https://en.wikipedia.org/wiki/Literate_programming).
- Pre-configured TOML files are written to `rulesets/*.toml`.
In future PRs, users could also share TOML configurations by adding them directly to that location, without wrapper scripts or explanation.
- Rename `RULES.md` to `MANUAL.md` since it now contains more than just rules.
- Move some of the detailed information from the README into the MANUAL.
New users, or people just having a quick look at the GitHub page just need a brief overview with a pointer to detailed information.
This also paves the way for generating a PDF version of the manual for 2 reasons:
  1. Many engineers really like having a printed copy on their desk.
  2. A PDF with clickable table of contents is much easier to navigate than GitHub's hamburger menu.
- The manual contains a section describing how rulesets are specified.
- Wrapper script templates are provided for POSIX shells (not just Bash) and Window's "cmd.exe" shell.
I'm not a PowerShell expert, but the mechanism in `mdgen` should be straightforward to extend.

### CODE REVIEW

**Comment by dalance** [comment]
Looks good!!!

Some features implemented by shell script seems to be able to handled by svlint directly.
For example, 

* plane text filelist dump like `--dump-filelist text`
* style_max_width rule
* verbose UTF-8 error handling

How about it?

**Comment by DaveMcEwan** [comment]
`--dump-filelist`:
Do you mean the use of `STRIP_ANSI_CONTROL` and `STRIP_ASCII_CONTROL` when building up the list `SVFILES` in the parseonly and style wrapper scripts?
The calls to `term.reset()`/`dat.clear()` in `src/printer.rs` will put control codes onto STDOUT (even though they're normally invisible), so my thinking is to sanitize as much as possible - particularly if other users might use those as examples.
We could have a mode that doesn't intentionally emit control codes (an option like `--nocolor`?), but I would like to keep sanitization in the scripts just to avoid potential issues.

style_max_width rule:
I wanted to do this :p but I can't think of a neat way to do it before the preprocessor.
Do you have something in mind?

Verbose UTF-8 error handling:
This is a real issue we've discovered working between sites which use LATIN1 for some files that give some obscure errors from a low-level dependency (nom? I can't remember).
You're right, this would be much nicer to handle directly (extend `sv_parser_error::Error`?) plus that would solve the Windows issue too.

Thinking ahead where users might want all sorts of other stuff in wrapper scripts, I think it would be nice to have an example of passing `SVFILES` through `xargs` that they can copy (like this PR has for UTF-8 checks).
I guess these examples should instead be in `md/manual-rulesets.md`.
Other stuff I can think of might include:
- Running other lint tools like Verilator, Questa, etc.
- Reporting metrics like the number of lines.
- Checking that each file is under version control.
- Searching for "magic" strings for other flows, e.g. documentation tools.

For the `--dump-filelist`/sanitization and UTF-8 comments, would you accept this PR if I open issues on svlint and sv-parser?
Fon the style_max_width comment, I'm not sure how to resolve!

**Comment by dalance** [comment]
> Do you mean the use of STRIP_ANSI_CONTROL and STRIP_ASCII_CONTROL when building up the list SVFILES in the parseonly and style wrapper scripts?

If you want to keep `STRIP*` to avoid potential issue, I agree it.
At least, I think `FILES_FROM_YAML`  can be removed by adding plane text output.

> style_max_width rule

The current `Linter` targets to check syntax tree, so checking before preprocess is difficult.
 So the check like `Linter::check_str()` can be added before `parse_sv` at https://github.com/dalance/svlint/blob/b0f560f5c27f165e60182ab54c49102d77869868/src/main.rs#L248

```
// read str from path
let str_failed = Linter::check_str(&text);
match parse_sv_str(&text,,,) {
```

If there are many checks at this point, expandable system like `Rule` may be required.
Currently, I think adding text width check in `Linter::check_str()` directly is sufficient.

**Comment by DaveMcEwan** [comment]
Checks on merge to master are currently expected to fail because they depend on #229.

Can we leave something like `Linter::check_str()` for a later PR? As you mention, an expandable system is the nicer solution, but that's a much bigger chunk of work!

**Comment by dalance** [comment]
> Can we leave something like Linter::check_str() for a later PR?

No problem. I'll merge this PR after CI pass.

**Pull request merged**
